DavidThomasSL/intern-project

- client/index.html
- client/js/client.js
> Signin flow

- client/index.html
- client/js/config/routeConfig.js
- client/js/controllers/mainController.js
- client/js/services/gameService.js
- client/js/services/routingService.js
- client/js/services/userService.js
- client/templates/question.html
- client/templates/room.html
- server/GameController.js
- server/server.js
Added a game controller for the room on the server, which handles game
logic for users (dealing hands, getting new questions, controlling user scores).
Added gameservice to client to hold game questions, rounds ect
Added question page to show question and user hand
> Added Start Game Funcationality

- package.json
- server/BlackWhiteCards.json
- server/GameController.js
- server/server.js
Added the full set of black and white cards locally as json
Each user now has a individual hand at the start of each game
Questions are fetched randomly from json (no order)
> Card's Against Humanity json

- server/GameController.js
Removes chance of players getting dealt duplicate cards in initial deal.
Also removes chance of getting the same question twice.
Should fix #36
> Removed duplicate cards in initial deal

- Gruntfile.js
- package.json
- server.js
- server/server.js
- test/conf.js
Are now two types of build, test and prod, the prod test is run by
circleCi and runs the server with only info logging, making it much
clearer. Protractor tests are now more verbose, and can see what test is
currently running, better for debugging
> Added Server logging levels + verbose test output

- circle.yml
This allows use to have a dev instance to trial beta features before
pushing to the master, or production, instance. Allows for more stability
with master branch
> Pushing to dev builds and starts a dev instance

- README.md
- client/index.html
Added tag for to mark point where we have a basic functioning game
> fixed readme and site logo

- Gruntfile.js
- client/Angular/config/routeConfig.js
- client/Angular/controllers/mainController.js
- client/Angular/services/gameService.js
- client/Angular/services/routingService.js
- client/Angular/services/userService.js
- client/includes/templates/results.html
- client/includes/templates/wait_question.html
- client/includes/templates/wait_vote.html
- client/index.html
- server/GameController.js
- server/server.js
Made some variable and event names more clear.
Made voting and choice waiting pages separate.
Adding a counter to see how many people are left to make a choice.
> Submission counter

- client/Angular/controllers/mainController.js
- client/Angular/services/gameService.js
- client/Angular/services/roomService.js
- client/Angular/services/userService.js
- client/includes/css/test-site.css
- client/includes/templates/game_question.html
- client/includes/templates/vote_favourite.html
Added very basic bootstrap styles to the answer submission and voting pages
> Bootstrap voting

- client/includes/templates/game_question.html
- client/includes/templates/vote_favourite.html
Reverts DavidThomasSL/intern-project#64
> Revert "added a submit button so users can change their mind"

- client/includes/templates/results.html
- client/includes/templates/vote_favourite.html
- client/includes/templates/wait_question.html
- client/includes/templates/wait_vote.html
- client/index.html
- server/GameController.js
Only use pick 1 questions cards until we get multiple picks working
some basic bootstrap changes
> Avoid pick 2 cards, some bootstrap

- client/includes/templates/results.html
- client/includes/templates/vote_favourite.html
- client/includes/templates/wait_question.html
- client/includes/templates/wait_vote.html
Players now can't leave a game once it has started and can only finish the game at the end of a round.
> Removed quit and finish game buttons mid game

- client/includes/css/test-site.css
- client/includes/templates/game/game_question.html
This reverts commit ef4c6874c8ad02e62243c00324043e82e8f28f14.
Hopefully this didn't break anything
> Revert "removed unused css"

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/Angular/services/gameService.js
- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/game/results.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/room/room_lobby.html
- client/index.html
- server/GameController.js
- server/server.js
- test/karma/karma.gameService.spec.js
- test/protractor/afterGameSpec.js
- test/protractor/afterRoundSpec.js
- test/protractor/helpers/browserHelper.js
- test/protractor/playingGameSpec.js
- test/protractor/ptor.conf.js
- test/protractor/startingGameSpec.js
Made sure that each player needs to be ready before moving on.
Moved some flow logic to the server so client can't just call finishGame(),nextRound() etc whenever they want, only can say that they are ready to move on.
Made the sidebar update the scores after each vote instead of after each round but visual rank still doesn't work completely.
Removed ng-enter and ng-leave animations for now until flicker is fixed.
> Player readying system

- server/GameController.js
- server/server.js
Instead of testing the game state and send back certain types of data, now we just send everything back to the client. This reduces a lot of repetition in the code, and ensures the client has all the game information at all times, catching small bugs where they did have playerRoundResults at certain points.
> simplify rejoin code to send all game data to client

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/Angular/services/gameService.js
- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/game/game_question.html
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/room/room_lobby.html
- client/includes/templates/signup/join_create_room.html
- client/includes/templates/signup/set_name.html
- client/index.html
- server/GameController.js
- server/server.js
- test/protractor/afterGameSpec.js
- test/protractor/startingGameSpec.js
Can now see who is ready to move on in results screen.
Made text size and scaling more consistent across pages, removed unneeded text.
Added visual to see how many round are left.
Changed ready color to fit more with bootstrap.
Changed maxRounds back to 8 and trying 10 cards in hand to fit more with actual card game.
> After round ready visual

- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/game/results.html
- client/includes/templates/room/room_lobby.html
- client/index.html
- server/BlackWhiteCards.json
- server/GameController.js
- test/protractor/afterGameSpec.js
- test/protractor/afterRoundSpec.js
- test/protractor/joinRoomSpec.js
- test/protractor/playingGameSpec.js
- test/protractor/ptor.conf.js
- test/protractor/startingGameSpec.js
Added end to end tests for refreshing at each stage in the game.
Added tests for readying up at the start of the game and at the end of each round. 
Made people able to have the same rank if they have the same score. #98 
Added tests for ranking, round display and sidebar.
> More end to end tests and ranking fix

- client/Angular/services/communicationService.js
- client/Angular/services/gameService.js
- client/Angular/services/routingService.js
- client/Angular/services/userService.js
- client/includes/templates/room/room_lobby.html
- package.json
- server/GameController.js
- server/Room.js
- server/User.js
- server/server.js
The user and room objects are now in their own js files, and provide handy
default functions, such as adding a user to a room, broadcasting to all
users in a room, sending user details etc
Users also use unique ids now, not just incremental, stopping issues when
two people could have the same id when joining again
> User and Room Objects

- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/game/game_question.html
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/room/room_lobby.html
- client/includes/templates/signup/join_create_room.html
- client/includes/templates/signup/set_name.html
- client/index.html
- server/BlackWhiteCards.json
Made it so the round, rank, sidebar etc. show up better on tablets and phones.
Removed some unused css, changed sidebar icon to glyph icon so it displays on other devices.
Fixed bug where names weren't displayed in results page.
> Device formattting, name display fix

- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- server/GameController.js
- server/server.js
If a player doesn't vote in a round they now lose 50 points.
Even if not everyone submits a vote the round results are sent when the timer ends, this means the ranks are displayed at the right time and round results should stay up to date.
Updated some broken titles and ordering.
> Non-voting penalisation

- client/Angular/controllers/roomController.js
- client/Angular/services/roomService.js
- client/includes/css/test-site.css
- client/includes/templates/room/room_lobby.html
- server/GameController.js
- server/Room.js
- server/server.js
- test/protractor/afterGameSpec.js
- test/protractor/botsSpec.js
- test/protractor/helpers/browserHelper.js
- test/protractor/joinRoomSpec.js
- test/protractor/roomCreateSpec.js
- test/protractor/startingGameSpec.js
Users can select the number of rounds they want to play from the game lobby, defaulted to 8
Moved bot and round selector up to info panel in lobby
Reduced number of rounds played during tests to help prevent jasmine timeouts
> Round select

- server/server.js
> Room code insensitive 

- server/CardController.js
- server/GameController.js
- server/Player.js
- server/Room.js
- server/User.js
- test/protractor/ptor.conf.js
Took out player and cardController from the GameController
Player is the same as before but now can call methods on it, bots are players too.
Cardcontroller handles loading and dishing out cards in one place
In prep for mocha tests
> GameController Splitting

- client/Angular/controllers/gameController.js
- client/Angular/controllers/roomController.js
- client/includes/templates/game/results.html
> add scroll to replace cards on result screen

- client/Angular/services/gameService.js
- client/includes/templates/game/results.html
- test/karma/karma.gameService.spec.js
just removes the possible "removed 0 cards" message if no cards are selected in the replace cards screen
> removed replace 0 card message

- client/includes/css/test-site.css
- client/includes/templates/game/game_question.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/user/progressBar.html
- client/index.html
- test/protractor/userInitialiseSpec.js
> Design changes

- client/Angular/controllers/gameController.js
- client/Angular/services/dynamicTextService.js
- client/Angular/services/gameService.js
- client/includes/css/test-site.css
- client/includes/templates/game/game_question.html
- client/includes/templates/game/vote_favourite.html
- server/GameController.js
- server/Player.js
- server/User.js
On the voting page can now see the submitted answers in the context of the question i.e. blanks filled in.
Refresh support for dynamic text on waiting page and voting page.
Moved the replace cards function into the player class.
> Can see complete answers on voting

- client/Angular/controllers/gameController.js
- client/Angular/controllers/roomController.js
- client/includes/templates/game/game_question.html
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/room/room_lobby.html
- client/includes/templates/user/userPanelLarge.html
- client/includes/templates/user/userPanelSmall.html
- client/includes/templates/user/userPanelSmallQuestion.html
- client/includes/templates/user/userPanelSmallVoted.html
Re-size dynamically based on screen size. On very small screens its 2 per row, on larger screens it 4 per row with a landscape layout. Try it and see.
fix #149
> User icons are smaller on small screens

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/Angular/controllers/roomController.js
- client/Angular/services/userService.js
- client/includes/templates/game/wait_vote.html
- server/GameController.js
> fixed timer issue on wait voting page

- client/Angular/controllers/mainController.js
- client/Angular/directives/userProfileDirective.js
- client/Angular/services/roomService.js
- client/includes/templates/user/userPanelLarge.html
- client/includes/templates/user/userPanelSmall.html
- client/includes/templates/user/userPanelSmallQuestion.html
- client/includes/templates/user/userPanelSmallVoted.html
- client/index.html
- test/karma/karma.roomService.spec.js
- test/protractor/afterRoundSpec.js
Game rankings now open as soon as you open the navbar (fix #165)
User profile is also shown in the nav bar beside the name
User profile directive now just takes the user image, and not a function to retrieve that image
> Rankings and UserImage in Navbar

- server/GameController.js
- server/Player.js
Fixes issue where 2 players are in game and only one submits answer in the time limit. 
During voting, only the player who didn't submit  an answer can vote, the player who did can't.
However, the game would still wait for the full time, as the number of votes didn't match the number of players, even though one player COULDNT vote (can't vote for their own).
This fixes that issue by checking for all players who have not yet voted, is it possible for them to even submit a vote? If it is not possible (i.e only answer available they submitted and cannot click) then the voting is cut short and it moves onto the results stage.
> Submit answer wait

- test/e2e/afterGameSpec.js
- test/e2e/botsSpec.js
- test/e2e/helpers/browserHelper.js
- test/e2e/observerSpec.js
- test/e2e/playingGameSpec.js
- test/e2e/startingGameSpec.js
Fixed issue where global test variables seem to be defined at different times causing conflicts between tests.
Now variables used in testing are just assigned within the 'it' statements when they are actually needed, should fix this issue.
> E2E test fix

- client/Angular/controllers/gameController.js
- client/Angular/services/dynamicTextService.js
- client/includes/css/test-site.css
- client/includes/templates/game/vote_favourite.html
user's answers in the voting panels are bolded and slightly larger, to stand out from the question text.
> Bold answers

- client/includes/css/test-site.css
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/index.html
Improved the layout of the results page, changed it from a table to a list including avatars.
Fixed round displaying as -1 issue.
> New results layout

- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/game/game_question.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/user/userPanelSmallQuestion.html
- client/includes/templates/user/userPanelSmallVoted.html
- test/e2e/afterGameSpec.js
Updated the look of the end game screen to contain avatars similar to round results page.
Only shows avatar and not name on waiting screen so can fit more in a smaller space.
> End game update

- client/includes/templates/game/game_question.html
Fixed bug where when submitting answers, 0s show up after submitting
> Fixed answer positions appearing as 0

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/Angular/services/communicationService.js
- client/Angular/services/gameService.js
- client/Angular/services/userService.js
- client/includes/css/test-site.css
- client/includes/templates/game/endGame.html
- client/includes/templates/room/room_lobby.html
- server/server.js
- test/e2e/helpers/browserHelper.js
- test/e2e/playAgainSpec.js
- test/e2e/ptor.conf.js
- test/unit/frontend/karma.communicationService.spec.js
> Play again

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/Angular/services/gameService.js
- client/includes/templates/game/results.html
- server/GameController.js
- server/Player.js
- server/server.js
- test/e2e/afterRoundSpec.js
- test/e2e/helpers/browserHelper.js
- test/unit/frontend/karma.gameService.spec.js
- test/unit/server/mocha.Player.spec.js
Removed mechanic of replacing individual cards, now just one button for replacing entire hand.
> Changed from replace cards to replace hand button

- server/GameController.js
Fixed bug where player could have a rank lower than the amount of players in the room.
Now only assigns ranks if the players are 'connectedtoserver'
> Fixed rank bug

- client/includes/templates/game/game_question.html
Puts the replace hand button on the left.
jk, it centers it
> center replace hand button

- client/includes/templates/game/game_question.html
- client/includes/templates/observer/roomOverviewPanel.html
- test/e2e/playingGameSpec.js
Took it out so we can make a release
> Remove replace cards

- client/includes/templates/room/room_lobby.html
Just moving ready button above the player list so its more obvious in the room lobby
> Ready button more obvious

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
Making sure when players click 'play again' button or toast that all ranking and scoring data is removed.
> Data clear on play again

- client/Angular/controllers/mainController.js
- client/includes/templates/game/game_question.html
- client/includes/templates/user/messenger.html
- server/GameController.js
- server/server.js
- test/e2e/helpers/browserHelper.js
- test/e2e/playingGameSpec.js
Fixes bug where counter would reset when clicking replace cards.
Removed some unused code from server.
Made some tests more explicit that seemed to sometimes be failing locally.
> Replace cards counter bug fix

- client/includes/templates/game/game_question.html
- server/CardController.js
Deals with edge case where players manage to exhaust the entire card pool, now it just resets the cards once they run out
> Running out of cards

- client/Angular/controllers/mainController.js
- client/includes/templates/game/game_question.html
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- test/unit/frontend/karma.mainController.spec.js
Fixed the bug on the waiting pages for question and voting where the timer value was lost on refresh.
> Waiting page timer fix

- client/Angular/controllers/observerController.js
- client/includes/templates/observer/observer_lobby.html
- client/includes/templates/observer/observer_question.html
- client/includes/templates/observer/observer_voting.html
- client/includes/templates/room/join_create_room.html
- client/includes/templates/room/room_lobby.html
- server/Room.js
Fixes timers on all observer screens.
Fixes visualization order for observer screens.
Fixed some formatting on the observer screens.
> Observer bug fixes

- client/Angular/controllers/mainController.js
- server/GameController.js
- server/Room.js
- server/Round.js
- server/server.js
- test/e2e/joinInProgressSpec.js
Now instead of people joining games as observers they can join as players.
As soon as a player joins everyone gets a toast telling them and everyone's score and ranking data updates.
> Players joining in progress

- test/e2e/afterRoundSpec.js
Will maybe fix the timing issue we are having on circle ci
> Timing test fix

- client/includes/templates/user/userPanelSmall.html
Fixed problem where avatars weren't centered on small screens
> Centered mobile avatars in lobby

- client/Angular/controllers/gameController.js
- client/Angular/controllers/mainController.js
- client/includes/templates/game/endGame.html
- client/includes/templates/game/game_question.html
- client/includes/templates/game/results.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/game/wait_question.html
- client/includes/templates/game/wait_vote.html
- client/includes/templates/observer/observer_endGame.html
- client/includes/templates/observer/observer_lobby.html
- client/includes/templates/observer/observer_question.html
- client/includes/templates/observer/observer_results.html
- client/includes/templates/observer/observer_voting.html
- client/includes/templates/room/room_lobby.html
- client/index.html
input staying if the next page loads
and fixed the problem with visualisation of own messeges
> fixed messenger i

- client/Angular/controllers/mainController.js
- client/includes/templates/game/endGame.html
- client/includes/templates/game/game_question.html
- client/includes/templates/game/vote_favourite.html
- client/includes/templates/observer/observer_endGame.html
- client/includes/templates/room/join_create_room.html
- client/includes/templates/room/room_lobby.html
- client/includes/templates/signup/set_name.html
the library we're using for animations does not support those versions
so all buttons with animations are not clickable
> disabled animations on iphones, ipads and ipods

- client/includes/css/test-site.css
- client/index.html
Should fix some tablet formatting issues for ipad but can't test on safari until its deployed
> Tablet formatting
